/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loja.Presentation;

import loja.Dominio.Util.PropertiesValidator;
import loja.Presentation.Controller.AcessoController;
import loja.Presentation.Controller.MenuController;
import loja.Presentation.Controller.PerfilController;
import loja.Presentation.Controller.TipoPagamentoController;
import java.util.logging.Level;
import java.util.logging.Logger;
import loja.Dominio.Model.MenuModel;
import loja.Dominio.Model.PerfilModel;
import loja.Dominio.Model.TipoAcessoModel;
import loja.Dominio.Model.TipoPagamentoModel;

/**
 *
 * @author Gustavo Nascimento
 */
public class Configuracao extends javax.swing.JFrame {

    /**
     * Creates new form Configuracao
     */
    public Configuracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPane = new javax.swing.JTabbedPane();
        jpnMenu = new javax.swing.JPanel();
        lblPagamento2 = new javax.swing.JLabel();
        txtMenu = new javax.swing.JTextField();
        btnCancelar3 = new javax.swing.JButton();
        btnSalvarMenu = new javax.swing.JButton();
        txtDescricaoMenu = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jCheckBox4 = new javax.swing.JCheckBox();
        btnPesquisarMenu = new javax.swing.JButton();
        jpnTipoAcesso = new javax.swing.JPanel();
        lblPagamento = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtNomeConf2 = new javax.swing.JTextField();
        btnSalvarAcesso = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txtNomeConf3 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        btnPesquisarAcesso = new javax.swing.JButton();
        jpnPagamento = new javax.swing.JPanel();
        lblPagamento3 = new javax.swing.JLabel();
        btnCancelar4 = new javax.swing.JButton();
        btnSalvarPagamento = new javax.swing.JButton();
        txtDescricaoPagamento = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jCheckBox2 = new javax.swing.JCheckBox();
        btnPesquisarPagamento = new javax.swing.JButton();
        jpnPerfil = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txtPerfil = new javax.swing.JTextField();
        lblPagamento1 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        txtDescricaoPerfil = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnPesquisarPerfil = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnSalvarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPane.setBackground(new java.awt.Color(0, 0, 102));
        tblPane.setForeground(new java.awt.Color(255, 255, 255));

        jpnMenu.setBackground(new java.awt.Color(241, 247, 249));

        lblPagamento2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblPagamento2.setText("Menu:");

        txtMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMenu.setForeground(new java.awt.Color(255, 255, 255));
        txtMenu.setText("ADM");
        txtMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnCancelar3.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar3.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar3.setText("Cancelar");
        btnCancelar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar3.setBorderPainted(false);
        btnCancelar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        btnSalvarMenu.setBackground(new java.awt.Color(61, 189, 61));
        btnSalvarMenu.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarMenu.setText("Salvar");
        btnSalvarMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvarMenu.setBorderPainted(false);
        btnSalvarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMenuActionPerformed(evt);
            }
        });

        txtDescricaoMenu.setBackground(new java.awt.Color(0, 0, 0));
        txtDescricaoMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 18))); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        txtDescricaoMenu.setViewportView(jTextArea3);

        jTable6.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jTable6.setForeground(new java.awt.Color(255, 255, 255));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable6.setGridColor(new java.awt.Color(0, 0, 0));
        jTable6.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable6.setShowGrid(true);
        jScrollPane6.setViewportView(jTable6);

        jCheckBox4.setBackground(new java.awt.Color(241, 247, 249));
        jCheckBox4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox4.setText("Excluir");

        btnPesquisarMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisarMenu.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnPesquisarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarMenu.setText("Pesquisar");
        btnPesquisarMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarMenu.setBorderPainted(false);
        btnPesquisarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnSalvarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox4)
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricaoMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnMenuLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblPagamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagamento2)
                    .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtDescricaoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        tblPane.addTab("Menu", new javax.swing.ImageIcon(getClass().getResource("/Presentation/produtos.png")), jpnMenu); // NOI18N

        jpnTipoAcesso.setBackground(new java.awt.Color(241, 247, 249));

        lblPagamento.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblPagamento.setText("Acesso");

        btnCancelar.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNomeConf2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNomeConf2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        btnSalvarAcesso.setBackground(new java.awt.Color(64, 87, 184));
        btnSalvarAcesso.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvarAcesso.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAcesso.setText("Salvar");
        btnSalvarAcesso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvarAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAcessoActionPerformed(evt);
            }
        });

        jTable4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N
        jTable4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Configuração", "True"},
                {"Gerente", "Relatório", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Perfil", "Menu", "Ativo"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(64, 87, 184));
        jTable4.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable4.setShowGrid(true);
        jScrollPane4.setViewportView(jTable4);

        txtNomeConf3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtNomeConf3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N

        jCheckBox3.setBackground(new java.awt.Color(241, 247, 249));
        jCheckBox3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox3.setText("Excluir");

        btnPesquisarAcesso.setBackground(new java.awt.Color(51, 153, 0));
        btnPesquisarAcesso.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnPesquisarAcesso.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarAcesso.setText("Pesquisar");
        btnPesquisarAcesso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTipoAcessoLayout = new javax.swing.GroupLayout(jpnTipoAcesso);
        jpnTipoAcesso.setLayout(jpnTipoAcessoLayout);
        jpnTipoAcessoLayout.setHorizontalGroup(
            jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                        .addComponent(btnSalvarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnPesquisarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                        .addComponent(txtNomeConf2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeConf3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBox3)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTipoAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTipoAcessoLayout.setVerticalGroup(
            jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPagamento)
                .addGap(18, 18, 18)
                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeConf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeConf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        tblPane.addTab("Acesso", jpnTipoAcesso);

        jpnPagamento.setBackground(new java.awt.Color(241, 247, 249));

        lblPagamento3.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblPagamento3.setText("Tipo Pagamento");

        btnCancelar4.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar4.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar4.setText("Cancelar");
        btnCancelar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar4ActionPerformed(evt);
            }
        });

        btnSalvarPagamento.setBackground(new java.awt.Color(51, 153, 0));
        btnSalvarPagamento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalvarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarPagamento.setText("Salvar");
        btnSalvarPagamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPagamentoActionPerformed(evt);
            }
        });

        txtDescricaoPagamento.setBackground(new java.awt.Color(255, 255, 255));
        txtDescricaoPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 18))); // NOI18N

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jTextArea4.setRows(5);
        txtDescricaoPagamento.setViewportView(jTextArea4);

        jTable7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jTable7.setForeground(new java.awt.Color(255, 255, 255));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable7.setGridColor(new java.awt.Color(0, 0, 0));
        jTable7.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable7.setShowGrid(true);
        jScrollPane7.setViewportView(jTable7);

        jCheckBox2.setBackground(new java.awt.Color(241, 247, 249));
        jCheckBox2.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox2.setText("Excluir");

        btnPesquisarPagamento.setBackground(new java.awt.Color(102, 102, 255));
        btnPesquisarPagamento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPesquisarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarPagamento.setText("Pesquisar");
        btnPesquisarPagamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnPagamentoLayout = new javax.swing.GroupLayout(jpnPagamento);
        jpnPagamento.setLayout(jpnPagamentoLayout);
        jpnPagamentoLayout.setHorizontalGroup(
            jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPagamentoLayout.createSequentialGroup()
                .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPagamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox2)
                            .addComponent(txtDescricaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnPagamentoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSalvarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnPagamentoLayout.createSequentialGroup()
                .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPagamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPagamentoLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblPagamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnPagamentoLayout.setVerticalGroup(
            jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPagamentoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPagamento3)
                .addGap(18, 18, 18)
                .addComponent(txtDescricaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        tblPane.addTab("Tipo Pagamento", new javax.swing.ImageIcon(getClass().getResource("/Presentation/produtos.png")), jpnPagamento); // NOI18N

        jpnPerfil.setBackground(new java.awt.Color(241, 247, 249));

        jTable3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jTable3.setShowGrid(true);
        jScrollPane3.setViewportView(jTable3);

        txtPerfil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPagamento1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblPagamento1.setText("PERFIL:");

        btnCancelar1.setBackground(new java.awt.Color(180, 36, 36));
        btnCancelar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setText("CANCELAR");
        btnCancelar1.setAutoscrolls(true);
        btnCancelar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        txtDescricaoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        txtDescricaoPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 18))); // NOI18N
        txtDescricaoPerfil.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        txtDescricaoPerfil.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        txtDescricaoPerfil.setViewportView(jTextArea2);

        btnPesquisarPerfil.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisarPerfil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarPerfil.setText("PESQUISAR");
        btnPesquisarPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPerfilActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(241, 247, 249));
        jCheckBox1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox1.setText("Excluir");

        btnSalvarPerfil.setBackground(new java.awt.Color(61, 189, 61));
        btnSalvarPerfil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarPerfil.setText("SALVAR");
        btnSalvarPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 1, true));
        btnSalvarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnPerfilLayout = new javax.swing.GroupLayout(jpnPerfil);
        jpnPerfil.setLayout(jpnPerfilLayout);
        jpnPerfilLayout.setHorizontalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnPerfilLayout.createSequentialGroup()
                                .addComponent(btnSalvarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnPesquisarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(txtDescricaoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpnPerfilLayout.setVerticalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagamento1))
                .addGap(30, 30, 30)
                .addComponent(txtDescricaoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tblPane.addTab("Perfil", jpnPerfil);

        getContentPane().add(tblPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar3ActionPerformed

    private void btnSalvarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMenuActionPerformed
        MenuModel menu = new MenuModel();

        try {
            if (menu.validString(txtMenu.getText())) {
                menu.setMenu(txtMenu.getText());
            }

            //        if (menu.validString(txtDescricaoMenu)) {
                //            menu.setMenu(txtMenu.getText());
                //        }
            MenuController menuController = new MenuController();

            menuController.Salvar(menu);

        } catch (PropertiesValidator ex) {
            Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarMenuActionPerformed

    private void btnPesquisarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarMenuActionPerformed
        MenuModel menu = new MenuModel();

        MenuController menuController = new MenuController();

        menuController.Pesquisar(menu);
    }//GEN-LAST:event_btnPesquisarMenuActionPerformed

    private void btnSalvarAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAcessoActionPerformed
        TipoAcessoModel acesso = new TipoAcessoModel();
        try {
            if (acesso.validInt(Integer.getInteger(txtPerfil.getText()))) {
                acesso.setIdPerfil(Integer.getInteger(txtMenu.getText()));
            }

            if (acesso.validInt(Integer.getInteger(txtMenu.getText()))) {
                acesso.setIdMenu(Integer.getInteger(txtMenu.getText()));
            }

            //        if (menu.validString(txtDescricaoMenu)) {
                //            menu.setMenu(txtMenu.getText());
                //        }
            AcessoController acessoController = new AcessoController();
            acessoController.Salvar(acesso);

        } catch (PropertiesValidator ex) {
            Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarAcessoActionPerformed

    private void btnPesquisarAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAcessoActionPerformed
        TipoAcessoModel acesso = new TipoAcessoModel();

        AcessoController acessoController = new AcessoController();
        acessoController.Pesquisar(acesso);
    }//GEN-LAST:event_btnPesquisarAcessoActionPerformed

    private void btnCancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar4ActionPerformed

    private void btnSalvarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPagamentoActionPerformed
        TipoPagamentoModel tipoPagamento = new TipoPagamentoModel();

        //        if (tipoPagamento.validString(txtDescricaoPagamento)) {
            //            tipoPagamento.setDescPagamento(txtDescricaoPagamento);
            //        }

        TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();

        tipoPagamentoController.Salvar(tipoPagamento);
    }//GEN-LAST:event_btnSalvarPagamentoActionPerformed

    private void btnPesquisarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPagamentoActionPerformed
        TipoPagamentoModel tipoPagamento = new TipoPagamentoModel();

        TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();

        tipoPagamentoController.Pesquisar(tipoPagamento);
    }//GEN-LAST:event_btnPesquisarPagamentoActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnPesquisarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPerfilActionPerformed

        try {
            PerfilModel perfil = new PerfilModel();

            if (perfil.validString(txtPerfil.getText())) {
                perfil.setPerfile(txtPerfil.getText());
            }
            //            if (perfil.validString(txtDescricaoPerfil)) {
                //              perfil.setPerfile(txtPerfil.getText());
                //            }

            PerfilController perfilController = new PerfilController();

            perfilController.Pesquisar(perfil);

        } catch (PropertiesValidator ex) {
            Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPesquisarPerfilActionPerformed

    private void btnSalvarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPerfilActionPerformed
        try {
            PerfilModel perfil = new PerfilModel();

            if (perfil.validString(txtPerfil.getText())) {
                perfil.setPerfile(txtPerfil.getText());
            }
            //            if (perfil.validString(txtDescricaoPerfil)) {
                //              perfil.setPerfile(txtPerfil.getText());
                //            }

            PerfilController perfilController = new PerfilController();

            perfilController.Salvar(perfil);

        } catch (PropertiesValidator ex) {
            Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar3;
    private javax.swing.JButton btnCancelar4;
    private javax.swing.JButton btnPesquisarAcesso;
    private javax.swing.JButton btnPesquisarMenu;
    private javax.swing.JButton btnPesquisarPagamento;
    private javax.swing.JButton btnPesquisarPerfil;
    private javax.swing.JButton btnSalvarAcesso;
    private javax.swing.JButton btnSalvarMenu;
    private javax.swing.JButton btnSalvarPagamento;
    private javax.swing.JButton btnSalvarPerfil;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnPagamento;
    private javax.swing.JPanel jpnPerfil;
    private javax.swing.JPanel jpnTipoAcesso;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPagamento1;
    private javax.swing.JLabel lblPagamento2;
    private javax.swing.JLabel lblPagamento3;
    private javax.swing.JTabbedPane tblPane;
    private javax.swing.JScrollPane txtDescricaoMenu;
    private javax.swing.JScrollPane txtDescricaoPagamento;
    private javax.swing.JScrollPane txtDescricaoPerfil;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtNomeConf2;
    private javax.swing.JTextField txtNomeConf3;
    private javax.swing.JTextField txtPerfil;
    // End of variables declaration//GEN-END:variables
}
