/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

/**
 *
 * @author Gustavo Nascimento
 */
public class Configuracao extends javax.swing.JFrame {

    /**
     * Creates new form Configuracao
     */
    public Configuracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPane = new javax.swing.JTabbedPane();
        jpnPerfil = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txtNomeConf1 = new javax.swing.JTextField();
        imgPagamento1 = new javax.swing.JLabel();
        lblPagamento1 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        btnSalvar4 = new javax.swing.JButton();
        txtaDescrição = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jpnTipoAcesso = new javax.swing.JPanel();
        lblPagamento = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        imgPagamento2 = new javax.swing.JLabel();
        txtNomeConf2 = new javax.swing.JTextField();
        btnSalvar5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnCancelar2 = new javax.swing.JButton();
        txtNomeConf3 = new javax.swing.JTextField();
        jpnMenu = new javax.swing.JPanel();
        imgPagamento3 = new javax.swing.JLabel();
        lblPagamento2 = new javax.swing.JLabel();
        txtNomeConf4 = new javax.swing.JTextField();
        btnCancelar3 = new javax.swing.JButton();
        btnSalvar6 = new javax.swing.JButton();
        txtaDescrição1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jpnPagamento = new javax.swing.JPanel();
        imgPagamento4 = new javax.swing.JLabel();
        lblPagamento3 = new javax.swing.JLabel();
        btnCancelar4 = new javax.swing.JButton();
        btnSalvar7 = new javax.swing.JButton();
        txtaDescrição2 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPane.setBackground(new java.awt.Color(79, 109, 234));

        jpnPerfil.setBackground(new java.awt.Color(79, 109, 234));

        jTable3.setBackground(new java.awt.Color(64, 87, 184));
        jTable3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(64, 87, 184));
        jTable3.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable3.setShowGrid(true);
        jScrollPane3.setViewportView(jTable3);

        txtNomeConf1.setBackground(new java.awt.Color(79, 109, 234));
        txtNomeConf1.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        txtNomeConf1.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeConf1.setText("ADM");
        txtNomeConf1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        imgPagamento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPagamento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/perfil.png"))); // NOI18N

        lblPagamento1.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        lblPagamento1.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento1.setText("Perfil");

        btnCancelar1.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar1.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar1.setOpaque(true);

        btnSalvar4.setBackground(new java.awt.Color(64, 87, 184));
        btnSalvar4.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvar4.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar4.setText("Salvar");
        btnSalvar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar4.setContentAreaFilled(false);

        txtaDescrição.setBackground(new java.awt.Color(79, 109, 234));
        txtaDescrição.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextArea2.setBackground(new java.awt.Color(79, 109, 234));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.");
        txtaDescrição.setViewportView(jTextArea2);

        javax.swing.GroupLayout jpnPerfilLayout = new javax.swing.GroupLayout(jpnPerfil);
        jpnPerfil.setLayout(jpnPerfilLayout);
        jpnPerfilLayout.setHorizontalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaDescrição)
                            .addGroup(jpnPerfilLayout.createSequentialGroup()
                                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                                        .addComponent(txtNomeConf1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                                        .addComponent(imgPagamento1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPagamento1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jpnPerfilLayout.setVerticalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgPagamento1)
                    .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPagamento1)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtaDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnSalvar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        tblPane.addTab("Perfil", jpnPerfil);

        jpnTipoAcesso.setBackground(new java.awt.Color(79, 109, 234));

        lblPagamento.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        lblPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento.setText("Acesso");

        btnCancelar.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setOpaque(true);

        imgPagamento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPagamento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/acesos.png"))); // NOI18N

        txtNomeConf2.setBackground(new java.awt.Color(79, 109, 234));
        txtNomeConf2.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        txtNomeConf2.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeConf2.setText("ADM");
        txtNomeConf2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnSalvar5.setBackground(new java.awt.Color(64, 87, 184));
        btnSalvar5.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvar5.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar5.setText("Salvar");
        btnSalvar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar5.setContentAreaFilled(false);

        jTable4.setBackground(new java.awt.Color(64, 87, 184));
        jTable4.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Configuração", "True"},
                {"Gerente", "Relatório", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Perfil", "Menu", "Ativo"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(64, 87, 184));
        jTable4.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable4.setShowGrid(true);
        jScrollPane4.setViewportView(jTable4);

        btnCancelar2.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar2.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar2.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar2.setText("Cancelar");
        btnCancelar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar2.setContentAreaFilled(false);
        btnCancelar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar2.setOpaque(true);

        txtNomeConf3.setBackground(new java.awt.Color(79, 109, 234));
        txtNomeConf3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        txtNomeConf3.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeConf3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jpnTipoAcessoLayout = new javax.swing.GroupLayout(jpnTipoAcesso);
        jpnTipoAcesso.setLayout(jpnTipoAcessoLayout);
        jpnTipoAcessoLayout.setHorizontalGroup(
            jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                            .addComponent(txtNomeConf2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomeConf3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                            .addComponent(imgPagamento2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPagamento))
                        .addComponent(btnSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(293, 293, 293)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTipoAcessoLayout.setVerticalGroup(
            jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(574, Short.MAX_VALUE))
                    .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnTipoAcessoLayout.createSequentialGroup()
                                .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPagamento)
                                    .addComponent(imgPagamento2))
                                .addGap(32, 32, 32)))
                        .addGap(1, 1, 1)
                        .addGroup(jpnTipoAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeConf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeConf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        tblPane.addTab("Acesso", jpnTipoAcesso);

        jpnMenu.setBackground(new java.awt.Color(79, 109, 234));

        imgPagamento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPagamento3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/menu.png"))); // NOI18N

        lblPagamento2.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        lblPagamento2.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento2.setText("Menu");

        txtNomeConf4.setBackground(new java.awt.Color(79, 109, 234));
        txtNomeConf4.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        txtNomeConf4.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeConf4.setText("ADM");
        txtNomeConf4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnCancelar3.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar3.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar3.setText("Cancelar");
        btnCancelar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar3.setContentAreaFilled(false);
        btnCancelar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar3.setOpaque(true);
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        btnSalvar6.setBackground(new java.awt.Color(64, 87, 184));
        btnSalvar6.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvar6.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar6.setText("Salvar");
        btnSalvar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar6.setContentAreaFilled(false);

        txtaDescrição1.setBackground(new java.awt.Color(79, 109, 234));
        txtaDescrição1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextArea3.setBackground(new java.awt.Color(79, 109, 234));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.");
        txtaDescrição1.setViewportView(jTextArea3);

        jTable6.setBackground(new java.awt.Color(64, 87, 184));
        jTable6.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jTable6.setForeground(new java.awt.Color(255, 255, 255));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable6.setGridColor(new java.awt.Color(64, 87, 184));
        jTable6.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable6.setShowGrid(true);
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1302, 1302, 1302))
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeConf4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtaDescrição1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnMenuLayout.createSequentialGroup()
                                        .addComponent(imgPagamento3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPagamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPagamento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgPagamento3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(txtNomeConf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtaDescrição1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSalvar6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        tblPane.addTab("Menu", new javax.swing.ImageIcon(getClass().getResource("/Presentation/produtos.png")), jpnMenu); // NOI18N

        jpnPagamento.setBackground(new java.awt.Color(79, 109, 234));

        imgPagamento4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPagamento4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/compras.png"))); // NOI18N

        lblPagamento3.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        lblPagamento3.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento3.setText("Tipo Pagamento");

        btnCancelar4.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar4.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnCancelar4.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar4.setText("Cancelar");
        btnCancelar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar4.setContentAreaFilled(false);
        btnCancelar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar4.setOpaque(true);
        btnCancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar4ActionPerformed(evt);
            }
        });

        btnSalvar7.setBackground(new java.awt.Color(64, 87, 184));
        btnSalvar7.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        btnSalvar7.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar7.setText("Salvar");
        btnSalvar7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar7.setContentAreaFilled(false);

        txtaDescrição2.setBackground(new java.awt.Color(79, 109, 234));
        txtaDescrição2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rubik Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextArea4.setBackground(new java.awt.Color(79, 109, 234));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.");
        txtaDescrição2.setViewportView(jTextArea4);

        jTable7.setBackground(new java.awt.Color(64, 87, 184));
        jTable7.setFont(new java.awt.Font("Rubik Light", 1, 14)); // NOI18N
        jTable7.setForeground(new java.awt.Color(255, 255, 255));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ADM", "Administrador do sistem", "True"},
                {"Gerente", "Gerente geral", "False"},
                {"Caixa", "Registrador de caixa", "True"}
            },
            new String [] {
                "Nome", "Descrição", "Ativo"
            }
        ));
        jTable7.setGridColor(new java.awt.Color(64, 87, 184));
        jTable7.setSelectionForeground(new java.awt.Color(64, 87, 184));
        jTable7.setShowGrid(true);
        jScrollPane7.setViewportView(jTable7);

        javax.swing.GroupLayout jpnPagamentoLayout = new javax.swing.GroupLayout(jpnPagamento);
        jpnPagamento.setLayout(jpnPagamentoLayout);
        jpnPagamentoLayout.setHorizontalGroup(
            jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPagamentoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPagamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1302, 1302, 1302))
                    .addGroup(jpnPagamentoLayout.createSequentialGroup()
                        .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtaDescrição2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPagamentoLayout.createSequentialGroup()
                                    .addComponent(imgPagamento4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblPagamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnPagamentoLayout.setVerticalGroup(
            jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPagamentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPagamento3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgPagamento4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btnCancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(txtaDescrição2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSalvar7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        tblPane.addTab("Tipo Pagamento", new javax.swing.ImageIcon(getClass().getResource("/Presentation/produtos.png")), jpnPagamento); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar3ActionPerformed

    private void btnCancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnCancelar3;
    private javax.swing.JButton btnCancelar4;
    private javax.swing.JButton btnSalvar4;
    private javax.swing.JButton btnSalvar5;
    private javax.swing.JButton btnSalvar6;
    private javax.swing.JButton btnSalvar7;
    private javax.swing.JLabel imgPagamento1;
    private javax.swing.JLabel imgPagamento2;
    private javax.swing.JLabel imgPagamento3;
    private javax.swing.JLabel imgPagamento4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnPagamento;
    private javax.swing.JPanel jpnPerfil;
    private javax.swing.JPanel jpnTipoAcesso;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPagamento1;
    private javax.swing.JLabel lblPagamento2;
    private javax.swing.JLabel lblPagamento3;
    private javax.swing.JTabbedPane tblPane;
    private javax.swing.JTextField txtNomeConf1;
    private javax.swing.JTextField txtNomeConf2;
    private javax.swing.JTextField txtNomeConf3;
    private javax.swing.JTextField txtNomeConf4;
    private javax.swing.JScrollPane txtaDescrição;
    private javax.swing.JScrollPane txtaDescrição1;
    private javax.swing.JScrollPane txtaDescrição2;
    // End of variables declaration//GEN-END:variables
}
